services:
  raimu:
    restart: unless-stopped 
    container_name: raimu 
    image: ghcr.io/giorgiobrux/raimu:latest
    hostname: raimu 
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # OpenAI API key for transcription/TTS (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Log level: trace, debug, info, warn, error (default: info)
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
      # Frontend
      traefik.enable: true 
      traefik.http.routers.raimu-http.entrypoints: web 
      traefik.http.routers.raimu-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker 
      traefik.http.routers.raimu-http.rule: Host(`raimu.${DOMAIN}`) 
      traefik.http.routers.raimu-http.service: raimu 
      traefik.http.routers.raimu.entrypoints: websecure 
      traefik.http.routers.raimu.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker 
      traefik.http.routers.raimu.rule: Host(`raimu.${DOMAIN}`) 
      traefik.http.routers.raimu.service: raimu 
      traefik.http.routers.raimu.tls.certresolver: cfdns 
      traefik.http.routers.raimu.tls.options: securetls@file 
      traefik.http.services.raimu.loadbalancer.server.port: 4173

      # WebSocket Backend
      traefik.http.routers.raimu-ws.rule: Host(`raimu.${DOMAIN}`) && PathPrefix(`/ws`)
      traefik.http.routers.raimu-ws.entrypoints: websecure
      traefik.http.routers.raimu-ws.tls: true
      traefik.http.services.raimu-ws.loadbalancer.server.port: 8080

      # PeerJS Server
      traefik.http.routers.raimu-peer.rule: Host(`peer.raimu.${DOMAIN}`)
      traefik.http.routers.raimu-peer.entrypoints: websecure
      traefik.http.routers.raimu-peer.tls: true
      traefik.http.services.raimu-peer.loadbalancer.server.port: 9000

networks: 
  saltbox:
    external: true